### Import Library

In [1]:
import pandas as pd
import joblib
from sklearn.preprocessing import LabelEncoder

### Memuat data hasil Feature Engineering

In [2]:
df = joblib.load('../dataset/step_04_engineered.pkl')
print("Data berhasil dimuat! Ukuran data:", df.shape)

Data berhasil dimuat! Ukuran data: (4864, 14)

### Seleksi Fitur

In [3]:
df = df[
    [
        'price',
        'district',
        'city',
        'bed_rooms',
        'bath_rooms',
        'carport',
        'land_area',
        'building_area',
        'total_rooms',
        'building_ratio',
        'remaining_land',
        'total_facilities',
        'total_area'
    ]
]

display(df.head())

,price,district,city,bed_rooms,bath_rooms,carport,land_area,building_area,total_rooms,building_ratio,remaining_land,total_facilities,total_area
0,2700000000,Jelambar,Jakarta Barat,4,2,0,100.0,225.0,6,2.250000,-125.0,6,325.0
1,2200000000,Jelambar,Jakarta Barat,3,3,0,60.0,140.0,6,2.333333,-80.0,6,200.0
2,1900000000,Jelambar,Jakarta Barat,3,2,0,60.0,120.0,5,2.000000,-60.0,5,180.0
3,2100000000,Tanjung Duren,Jakarta Barat,4,3,0,56.0,108.0,7,1.928571,-52.0,7,164.0
4,2650000000,Tanjung Duren,Jakarta Barat,4,4,0,67.0,149.0,8,2.223881,-82.0,8,216.0

### Verifikasi Jumlah Kategori

In [4]:
print("Jumlah District :", df['district'].nunique())
print("Jumlah City :", df['city'].nunique())

Jumlah District : 208
Jumlah City : 5

### Encoding District

In [5]:
le_district = LabelEncoder()
df['district'] = le_district.fit_transform(df['district'].astype(str))

### Encoding City

In [6]:
le_city = LabelEncoder()
df['city'] = le_city.fit_transform(df['city'].astype(str))

### Verifikasi Hasil Encoding

In [7]:
display(df.head())

,price,district,city,bed_rooms,bath_rooms,carport,land_area,building_area,total_rooms,building_ratio,remaining_land,total_facilities,total_area
0,2700000000,64,0,4,2,0,100.0,225.0,6,2.250000,-125.0,6,325.0
1,2200000000,64,0,3,3,0,60.0,140.0,6,2.333333,-80.0,6,200.0
2,1900000000,64,0,3,2,0,60.0,120.0,5,2.000000,-60.0,5,180.0
3,2100000000,194,0,4,3,0,56.0,108.0,7,1.928571,-52.0,7,164.0
4,2650000000,194,0,4,4,0,67.0,149.0,8,2.223881,-82.0,8,216.0

### Menyimpan Data Hasil Seleksi Fitur & Encoding

In [8]:
joblib.dump(df, '../dataset/step_05_selected.pkl')
print("\nData berhasil disimpan ke '../dataset/step_05_selected.pkl'!")

Data berhasil disimpan ke '../dataset/step_05_selected.pkl'!