### Import Library

In [1]:
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

### Memuat data hasil Seleksi Fitur dan Encoding

In [2]:
df = joblib.load('../dataset/step_05_selected.pkl')
print("Data berhasil dimuat! Ukuran data:", df.shape)

Data berhasil dimuat! Ukuran data: (4864, 13)

### Menentukan Fitur dan Target

In [3]:
# Fitur
X = df.drop('price', axis=1)

# Target 
y = df['price']

### Pembagian Data Training dan Testing

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

### Verifikasi Hasil Pembagian Data

In [5]:
print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)
print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

X_train : (3891, 12)
X_test  : (973, 12)
y_train : (3891,)
y_test  : (973,)

### Standarisasi Pada Fitur

In [6]:
scaler = StandardScaler()

# Standarisasi Data Training
X_train = pd.DataFrame(scaler.fit_transform(X_train), columns=X.columns, index=X_train.index)

# Standarisasi Data Testing
X_test = pd.DataFrame(scaler.transform(X_test), columns=X.columns, index=X_test.index)

### Verifikasi Hasil Standarisasi Fitur

In [7]:
print("\n=== Contoh Data X_train Setelah Scaling ===")
display(X_train.head())


print("\n=== Contoh Data X_test Setelah Scaling ===")
display(X_test.head())

=== Contoh Data X_train Setelah Scaling ===

,district,city,bed_rooms,bath_rooms,carport,land_area,building_area,total_rooms,building_ratio,remaining_land,total_facilities,total_area
2298,-0.171793,-1.181295,2.014383,1.599254,-0.145506,0.978025,1.281343,2.042002,0.100319,-0.758095,1.614048,1.280101
1831,1.591080,-1.181295,2.014383,1.599254,-0.145506,-0.455808,0.421922,2.042002,0.914107,-0.939854,1.614048,0.067209
3528,1.691816,-1.181295,2.014383,1.599254,-0.145506,1.490108,2.856949,2.042002,0.738153,-2.303045,1.614048,2.539643
180,-0.574736,0.116029,-0.410355,0.386253,1.171152,-0.742575,-0.509118,-0.013737,0.121735,-0.012884,0.489057,-0.669856
4400,1.456766,1.413353,-0.410355,0.386253,-1.462163,-0.332908,0.937574,-0.013737,1.321001,-1.485130,-0.635934,0.459066

=== Contoh Data X_test Setelah Scaling ===

,district,city,bed_rooms,bath_rooms,carport,land_area,building_area,total_rooms,building_ratio,remaining_land,total_facilities,total_area
2186,-1.380621,-0.532633,-0.410355,-0.826749,-1.462163,0.937058,-0.723974,-0.698983,-1.310933,1.750177,-1.198429,-0.044750
3353,-0.054268,-1.181295,0.802014,1.599254,-0.145506,-0.148558,-0.050760,1.356756,-0.062438,-0.067411,1.051553,-0.100730
2651,-0.574736,0.116029,0.802014,0.386253,1.171152,-0.763058,0.565158,0.671510,1.782147,-1.394251,1.051553,0.020559
2104,0.331885,-1.181295,-0.410355,0.386253,-0.145506,0.261109,0.250037,-0.013737,-0.153582,-0.085587,-0.073438,0.281797
4492,-1.330253,0.764691,-0.410355,-0.826749,-0.145506,-0.455808,-0.437500,-0.698983,-0.170943,0.150699,-0.635934,-0.492587

### Menyimpan Data Hasil Persiapan Model

In [8]:
joblib.dump((X_train, X_test, y_train, y_test), '../dataset/step_06_ready_for_model.pkl')
print("\nData siap pemodelan berhasil disimpan ke '../dataset/step_06_ready_for_model.pkl'!")

Data siap pemodelan berhasil disimpan ke '../dataset/step_06_ready_for_model.pkl'!